export const memedBattleAbi = [
  { inputs: [], stateMutability: "nonpayable", type: "constructor" },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "OwnableInvalidOwner",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "OwnableUnauthorizedAccount",
    type: "error",
  },
  { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "battleId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "memeA",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "memeB",
        type: "address",
      },
    ],
    name: "BattleChallenged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "battleId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "memeA",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "memeB",
        type: "address",
      },
    ],
    name: "BattleDraw",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "battleId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "memeA",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "memeB",
        type: "address",
      },
    ],
    name: "BattleRejected",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "battleId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "winner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "loser",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalReward",
        type: "uint256",
      },
    ],
    name: "BattleResolved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "battleId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "BattleRewardsClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "battleId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "memeA",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "memeB",
        type: "address",
      },
    ],
    name: "BattleStarted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "battleId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "PlatformFeeTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "battleId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "winner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalReward",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "participantCount",
        type: "uint256",
      },
    ],
    name: "RewardsDistributed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "battleId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "TokensBurned",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "from", type: "address" },
      { indexed: true, internalType: "address", name: "to", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amountOut",
        type: "uint256",
      },
    ],
    name: "TokensSwapped",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "battleId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "meme",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "nftsIds",
        type: "uint256[]",
      },
    ],
    name: "UserAllocated",
    type: "event",
  },
  {
    inputs: [],
    name: "BATTLE_COOLDOWN",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "BATTLE_DURATION",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ENGAGEMENT_WEIGHT",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "VALUE_WEIGHT",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_battleId", type: "uint256" },
      { internalType: "bool", name: "_accept", type: "bool" },
    ],
    name: "acceptOrRejectBattle",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_battleId", type: "uint256" },
      { internalType: "address", name: "_user", type: "address" },
      { internalType: "address", name: "_supportedMeme", type: "address" },
      { internalType: "uint256[]", name: "_nftsIds", type: "uint256[]" },
    ],
    name: "allocateNFTsToBattle",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "address", name: "", type: "address" },
      { internalType: "address", name: "", type: "address" },
    ],
    name: "battleAllocations",
    outputs: [
      { internalType: "uint256", name: "battleId", type: "uint256" },
      { internalType: "address", name: "user", type: "address" },
      { internalType: "address", name: "supportedMeme", type: "address" },
      { internalType: "bool", name: "claimed", type: "bool" },
      { internalType: "bool", name: "getBack", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "battleCooldowns",
    outputs: [
      { internalType: "bool", name: "onBattle", type: "bool" },
      { internalType: "uint256", name: "cooldownEndTime", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "battleCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "battleIds",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "battleResolver",
    outputs: [
      {
        internalType: "contract IMemedBattleResolver",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "battles",
    outputs: [
      { internalType: "uint256", name: "battleId", type: "uint256" },
      { internalType: "address", name: "memeA", type: "address" },
      { internalType: "address", name: "memeB", type: "address" },
      { internalType: "uint256", name: "memeANftsAllocated", type: "uint256" },
      { internalType: "uint256", name: "memeBNftsAllocated", type: "uint256" },
      { internalType: "uint256", name: "heatA", type: "uint256" },
      { internalType: "uint256", name: "heatB", type: "uint256" },
      { internalType: "uint256", name: "startTime", type: "uint256" },
      { internalType: "uint256", name: "endTime", type: "uint256" },
      { internalType: "enum BattleStatus", name: "status", type: "uint8" },
      { internalType: "address", name: "winner", type: "address" },
      { internalType: "uint256", name: "totalReward", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_memeA", type: "address" },
      { internalType: "address", name: "_memeB", type: "address" },
    ],
    name: "challengeBattle",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_battleId", type: "uint256" }],
    name: "claimRewards",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "factory",
    outputs: [
      { internalType: "contract IMemedFactory", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_battleId", type: "uint256" }],
    name: "getBattle",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "battleId", type: "uint256" },
          { internalType: "address", name: "memeA", type: "address" },
          { internalType: "address", name: "memeB", type: "address" },
          {
            internalType: "uint256",
            name: "memeANftsAllocated",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "memeBNftsAllocated",
            type: "uint256",
          },
          { internalType: "uint256", name: "heatA", type: "uint256" },
          { internalType: "uint256", name: "heatB", type: "uint256" },
          { internalType: "uint256", name: "startTime", type: "uint256" },
          { internalType: "uint256", name: "endTime", type: "uint256" },
          { internalType: "enum BattleStatus", name: "status", type: "uint8" },
          { internalType: "address", name: "winner", type: "address" },
          { internalType: "uint256", name: "totalReward", type: "uint256" },
        ],
        internalType: "struct Battle",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_battleId", type: "uint256" },
      { internalType: "address", name: "_user", type: "address" },
      { internalType: "address", name: "_meme", type: "address" },
    ],
    name: "getBattleAllocations",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "battleId", type: "uint256" },
          { internalType: "address", name: "user", type: "address" },
          { internalType: "address", name: "supportedMeme", type: "address" },
          { internalType: "uint256[]", name: "nftsIds", type: "uint256[]" },
          { internalType: "bool", name: "claimed", type: "bool" },
          { internalType: "bool", name: "getBack", type: "bool" },
        ],
        internalType: "struct UserBattleAllocation",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_battleId", type: "uint256" }],
    name: "getBattleScore",
    outputs: [
      { internalType: "uint256", name: "scoreA", type: "uint256" },
      { internalType: "uint256", name: "scoreB", type: "uint256" },
      { internalType: "uint256", name: "heatScoreA", type: "uint256" },
      { internalType: "uint256", name: "heatScoreB", type: "uint256" },
      { internalType: "uint256", name: "valueScoreA", type: "uint256" },
      { internalType: "uint256", name: "valueScoreB", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getBattles",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "battleId", type: "uint256" },
          { internalType: "address", name: "memeA", type: "address" },
          { internalType: "address", name: "memeB", type: "address" },
          {
            internalType: "uint256",
            name: "memeANftsAllocated",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "memeBNftsAllocated",
            type: "uint256",
          },
          { internalType: "uint256", name: "heatA", type: "uint256" },
          { internalType: "uint256", name: "heatB", type: "uint256" },
          { internalType: "uint256", name: "startTime", type: "uint256" },
          { internalType: "uint256", name: "endTime", type: "uint256" },
          { internalType: "enum BattleStatus", name: "status", type: "uint8" },
          { internalType: "address", name: "winner", type: "address" },
          { internalType: "uint256", name: "totalReward", type: "uint256" },
        ],
        internalType: "struct Battle[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getFactory",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_token", type: "address" },
      { internalType: "uint256", name: "_nftId", type: "uint256" },
    ],
    name: "getNftRewardAndIsReturnable",
    outputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "bool", name: "", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getResolver",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_token", type: "address" }],
    name: "getUserBattles",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "battleId", type: "uint256" },
          { internalType: "address", name: "memeA", type: "address" },
          { internalType: "address", name: "memeB", type: "address" },
          {
            internalType: "uint256",
            name: "memeANftsAllocated",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "memeBNftsAllocated",
            type: "uint256",
          },
          { internalType: "uint256", name: "heatA", type: "uint256" },
          { internalType: "uint256", name: "heatB", type: "uint256" },
          { internalType: "uint256", name: "startTime", type: "uint256" },
          { internalType: "uint256", name: "endTime", type: "uint256" },
          { internalType: "enum BattleStatus", name: "status", type: "uint8" },
          { internalType: "address", name: "winner", type: "address" },
          { internalType: "uint256", name: "totalReward", type: "uint256" },
        ],
        internalType: "struct Battle[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_user", type: "address" }],
    name: "getUserClaimableBattles",
    outputs: [
      { internalType: "uint256[]", name: "battleIdsArray", type: "uint256[]" },
      { internalType: "uint256[]", name: "rewardsArray", type: "uint256[]" },
      { internalType: "uint256", name: "totalReward", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_battleId", type: "uint256" },
      { internalType: "address", name: "_user", type: "address" },
    ],
    name: "getUserClaimableReward",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_user", type: "address" },
      { internalType: "address", name: "_token", type: "address" },
    ],
    name: "getUserClaimableRewards",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_user", type: "address" }],
    name: "getUserTokenAllocations",
    outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_tokenId", type: "uint256" },
      { internalType: "uint256", name: "_until", type: "uint256" },
    ],
    name: "getUserTokenBattleAllocations",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "winCount", type: "uint256" },
          { internalType: "uint256", name: "loseCount", type: "uint256" },
        ],
        internalType: "struct TokenBattleAllocation",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "nftBattleAllocations",
    outputs: [
      { internalType: "address", name: "supportedMeme", type: "address" },
      { internalType: "uint256", name: "battleId", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_battleId", type: "uint256" },
      { internalType: "address", name: "_actualWinner", type: "address" },
      { internalType: "uint256", name: "_totalReward", type: "uint256" },
    ],
    name: "resolveBattle",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_factory", type: "address" },
      { internalType: "address", name: "_resolver", type: "address" },
    ],
    name: "setFactoryAndResolver",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "tokenAllocations",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "tokenBattleAllocations",
    outputs: [
      { internalType: "uint256", name: "winCount", type: "uint256" },
      { internalType: "uint256", name: "loseCount", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "address", name: "", type: "address" },
    ],
    name: "userAllocationIndex",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "userBattles",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
] as const;
